import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Index
      <Link href="/page"><a style={{textDecoration:"underline"}}>to page</a></Link>
    </div>
  )
}

export default Home
