import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'


export default function Page2() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      Page2
      <Link href="/"><a style={{textDecoration:"underline"}}>to index</a></Link>
    </div>
  )
}
